[project]
name = "datasette-agent"
version = "0.1a4"
description = "An LLM-powered agent assistant for Datasette"
readme = "README.md"
authors = [{name = "Simon Willison"}]
license = "Apache-2.0"
classifiers=[
    "Framework :: Datasette"
]
requires-python = ">=3.10"
dependencies = [
    "datasette>=1.0a30",
    "datasette-llm>=0.1a7",
    "llm>=0.32a2",
    "python-ulid",
]

[tool.uv.sources]
llm = { path = "/Users/simon/dev/llm", editable = true }

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "llm-echo>=0.5a0",
    "inline-snapshot",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/datasette/datasette-agent"
Changelog = "https://github.com/datasette/datasette-agent/releases"
Issues = "https://github.com/datasette/datasette-agent/issues"
CI = "https://github.com/datasette/datasette-agent/actions"

[project.entry-points.datasette]
agent = "datasette_agent"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.packages.find]
include = ["datasette_agent*"]

[tool.setuptools.package-data]
datasette_agent = ["static/*", "templates/*"]
