/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConversationId = string;
export type Title = string | null;
export type Id = number;
export type ConversationId1 = string;
export type Role = string;
export type Content = string | null;
export type ToolName = string | null;
export type ToolArguments = string | null;
export type ToolOutput = string | null;
export type CreatedAt = string;
export type Messages = Message[];

export interface ConversationPageData {
  conversation_id: ConversationId;
  title: Title;
  messages: Messages;
  [k: string]: unknown;
}
export interface Message {
  id: Id;
  conversation_id: ConversationId1;
  role: Role;
  content?: Content;
  tool_name?: ToolName;
  tool_arguments?: ToolArguments;
  tool_output?: ToolOutput;
  created_at: CreatedAt;
  [k: string]: unknown;
}
