/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Title = string | null;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Conversations = ConversationSummary[];

export interface IndexPageData {
  conversations: Conversations;
  [k: string]: unknown;
}
export interface ConversationSummary {
  id: Id;
  title: Title;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  [k: string]: unknown;
}
